runner = 'DirectRunner'
project = 'coastal-volt-385014'
job_name = 'integration_unique_job1'
temp_location = 'gs://test-bardin22/temp'
region = 'asia-east2'
input_file = 'gs://test-bardin22/integration_app_logs.json'
google_service_key = '/Users/yegor/Downloads/wd/coastal-volt-385014-ebde26ba32f6.json'
output_dataset = 'logs'